services:
  db:
    image: postgres:15
    container_name: todo-db
    environment:
      POSTGRES_DB: todo_app_dev
      POSTGRES_USER: todo_user
      POSTGRES_PASSWORD: todo_password


  db-setup:
    image: postgres:15              # has psql inside
    depends_on:
      - db
    working_dir: /app
    volumes:
      - .:/app                      # mount your repo so script is visible
    environment:
      PGHOST: db
      PGUSER: todo_user
      PGPASSWORD: todo_password
      PGDATABASE: todo_app_dev
    command: ["bash", "./scripts/setup-database.sh", "dev"]

  backend:
    build: ./backend
    depends_on:
      - db-setup
    environment:
      DATABASE_URL: postgresql://todo_user:todo_password@db:5432/todo_app_dev
      CORS_ORIGINS: http://localhost:3000,http://127.0.0.1:3000

    ports:
      - "5000:5000"

  frontend:
    build: ./frontend
    depends_on:
      - backend
    environment:
      REACT_APP_API_URL: http://localhost:5000
    ports:
      - "3000:3000"
