#!/bin/bash

set -euo pipefail

if [ "$EUID" -ne 0 ]; then
    echo "[ERROR] This script must be run with sudo (root privileges)." >&2
    exit 1
fi

if [ -z "${SUDO_USER:-}" ]; then
    echo "[ERROR] Please run this script via sudo from a non-root user account." >&2
    exit 1
fi

TARGET_USER="$SUDO_USER"
TARGET_GROUP=$(id -gn "$TARGET_USER")
PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

API_URL="http://localhost:5000"
FRONTEND_URL="http://localhost:3000"
PLAYWRIGHT_URL="$FRONTEND_URL"

while [[ $# -gt 0 ]]; do
    case "$1" in
        --api-url)
            API_URL="$2"
            shift 2
            ;;
        --frontend-url)
            FRONTEND_URL="$2"
            shift 2
            ;;
        --playwright-url)
            PLAYWRIGHT_URL="$2"
            shift 2
            ;;
        --help|-h)
            cat <<'EOF'
Usage: sudo ./scripts/bootstrap.sh [options]

Options:
  --api-url URL         Base URL the frontend should use for API calls (default: http://localhost:5000)
  --frontend-url URL    Public URL where the frontend is served (default: http://localhost:3000)
  --playwright-url URL  URL Playwright tests should target (default: matches --frontend-url)
  -h, --help            Show this help message
EOF
            exit 0
            ;;
        *)
            echo "[ERROR] Unknown option: $1" >&2
            exit 1
            ;;
    esac
done

info() {
    echo "[INFO] $1"
}

success() {
    echo "[SUCCESS] $1"
}

error() {
    echo "[ERROR] $1" >&2
    exit 1
}

run_as_user() {
    local command="$1"
    runuser -u "$TARGET_USER" -- bash -lc "$command"
}

require_command() {
    local cmd="$1"
    if ! command -v "$cmd" >/dev/null 2>&1; then
        error "Required command '$cmd' was not found on PATH."
    fi
}

generate_secret() {
    python3 - <<'PY'
import secrets
print(secrets.token_urlsafe(32))
PY
}

require_command python3
require_command npm
require_command npx
require_command psql

info "Working directory: $PROJECT_ROOT"
info "Target user: $TARGET_USER"

info "Regenerating Python virtual environment..."
run_as_user "cd '$PROJECT_ROOT/backend' && rm -rf venv && python3 -m venv venv"

info "Installing backend dependencies..."
run_as_user "cd '$PROJECT_ROOT/backend' && source venv/bin/activate && pip install --upgrade pip && pip install -r requirements.txt"

info "Installing frontend dependencies..."
run_as_user "cd '$PROJECT_ROOT/frontend' && npm install"

info "Installing Playwright system dependencies..."
run_as_user "cd '$PROJECT_ROOT/frontend' && npx playwright install-deps"

info "Installing Playwright browsers..."
run_as_user "cd '$PROJECT_ROOT/frontend' && npx playwright install"

# info "Installing Playwright system dependencies..."
# (cd "$PROJECT_ROOT/frontend" && npx playwright install-deps)

info "Provisioning development database..."
"$PROJECT_ROOT/scripts/setup-database.sh" dev

info "Provisioning test database..."
"$PROJECT_ROOT/scripts/setup-database.sh" test

JWT_SECRET=$(generate_secret)
SECRET_KEY=$(generate_secret)

DEV_DB_URL="postgresql://todo_user:todo_password@localhost:5432/todo_app_dev"
TEST_DB_URL="postgresql://todo_user_test:todo_test_password@localhost:5432/todo_app_test"

FRONTEND_URL="${FRONTEND_URL%/}"
PLAYWRIGHT_URL="${PLAYWRIGHT_URL%/}"

CORS_ORIGINS_LIST=("http://localhost:3000" "http://127.0.0.1:3000")
if [[ ! " ${CORS_ORIGINS_LIST[*]} " =~ " ${FRONTEND_URL} " ]]; then
    CORS_ORIGINS_LIST+=("$FRONTEND_URL")
fi
CORS_ORIGINS=$(IFS=','; echo "${CORS_ORIGINS_LIST[*]}")

info "Writing backend environment file..."
cat > "$PROJECT_ROOT/backend/.env" <<EOF
# Generated by scripts/bootstrap.sh
DATABASE_URL=$DEV_DB_URL
TEST_DATABASE_URL=$TEST_DB_URL

JWT_SECRET=$JWT_SECRET
SECRET_KEY=$SECRET_KEY

FLASK_ENV=development
FLASK_APP=run.py
SQLALCHEMY_ECHO=false

CORS_ORIGINS=$CORS_ORIGINS
TASKS_PER_PAGE=50
EOF
chown "$TARGET_USER:$TARGET_GROUP" "$PROJECT_ROOT/backend/.env"

info "Writing frontend environment file..."
cat > "$PROJECT_ROOT/frontend/.env" <<EOF
# Generated by scripts/bootstrap.sh
REACT_APP_API_URL=$API_URL
EOF
chown "$TARGET_USER:$TARGET_GROUP" "$PROJECT_ROOT/frontend/.env"

info "Writing Playwright environment hints..."
cat > "$PROJECT_ROOT/frontend/.playwright.env" <<EOF
# Generated by scripts/bootstrap.sh
PLAYWRIGHT_BASE_URL=$PLAYWRIGHT_URL
PLAYWRIGHT_WEB_SERVER_URL=$PLAYWRIGHT_URL
EOF
chown "$TARGET_USER:$TARGET_GROUP" "$PROJECT_ROOT/frontend/.playwright.env"

info "Initializing development database schema..."
run_as_user "cd '$PROJECT_ROOT/backend' && source venv/bin/activate && python - <<'PY'
from app import create_app, db
app = create_app()
with app.app_context():
    db.create_all()
PY"

info "Bootstrap complete."
success "Backend venv, dependencies, databases, and environment files are ready."
