name: Dev Branch Pipeline

on:
  pull_request:
    branches:
      - dev
  workflow_dispatch:

jobs:
  python-lint:
    if: github.event_name == 'workflow_dispatch' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    uses: ./.github/workflows/python-lint.yaml

  eslint:
    if: github.event_name == 'workflow_dispatch' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    uses: ./.github/workflows/es-lint.yaml

  test-backend-unit:
    if: github.event_name == 'workflow_dispatch' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    uses: ./.github/workflows/backend-unit-tests.yml
    secrets: inherit

  test-frontend-unit:
    if: github.event_name == 'workflow_dispatch' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    uses: ./.github/workflows/frontend-unit-tests.yml

  test-backend-integration:
    if: github.event_name == 'workflow_dispatch' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    needs: [python-lint, eslint, test-backend-unit, test-frontend-unit]
    uses: ./.github/workflows/backend-integration-tests.yml
    secrets: inherit

  test-frontend-integration:
    if: github.event_name == 'workflow_dispatch' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    needs: [python-lint, eslint, test-backend-unit, test-frontend-unit]
    uses: ./.github/workflows/frontend-integration-tests.yml

  deploy:
    if: github.event_name == 'pull_request' && github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'
    uses: ./.github/workflows/development-deploy.yml
    secrets: inherit
    with:
      branch: dev

