name: Frontend Integration Tests
on:
  workflow_call:

jobs:
  test:
    runs-on: [self-hosted, Linux, X64]
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      working-directory: task-manager/frontend
      run: |
        npm install

    - name: Run integration tests
      working-directory: task-manager/frontend
      run: |
        npm run test:integration

