name: Release Branch Pipeline

on:
  pull_request:
    types: [opened, synchronize, closed]
    branches:
      - 'release**'

jobs:
  python-lint:
    if: github.event_name == 'pull_request' && github.event.action != 'closed'
    uses: ./.github/workflows/python-lint.yaml

  eslint:
    if: github.event_name == 'pull_request' && github.event.action != 'closed'
    uses: ./.github/workflows/es-lint.yaml

  test-backend-unit:
    if: github.event_name == 'pull_request' && github.event.action != 'closed'
    uses: ./.github/workflows/backend-unit-tests.yml
    secrets: inherit

  test-frontend-unit:
    if: github.event_name == 'pull_request' && github.event.action != 'closed'
    uses: ./.github/workflows/frontend-unit-tests.yml

  test-backend-integration:
    if: github.event_name == 'pull_request' && github.event.action != 'closed'
    needs: [python-lint, test-backend-unit]
    uses: ./.github/workflows/backend-integration-tests.yml
    secrets: inherit

  test-frontend-integration:
    if: github.event_name == 'pull_request' && github.event.action != 'closed'
    needs: [eslint, test-frontend-unit]
    uses: ./.github/workflows/frontend-integration-tests.yml

  test-e2e:
    if: github.event_name == 'pull_request' && github.event.action != 'closed'
    needs: [python-lint, eslint, test-backend-unit, test-frontend-unit, test-backend-integration, test-frontend-integration]
    uses: ./.github/workflows/e2e-tests.yml
    secrets: inherit

  generate-changelog:
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
    uses: ./.github/workflows/generate-changelog.yml
    secrets: inherit

